[workspace]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
channels = ["conda-forge"]
name = "go-pixi-template"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
start = "go run main.go"
test = "go test ./... -v"
fmt = "go fmt"
lint = { cmd = "golangci-lint run", depends-on = ["fmt"] }
lint-ci = "golangci-lint run"
lint-fix = "golangci-lint run --fix"

[dependencies]
go = ">=1.26.1,<2"
golangci-lint = ">=2.11.2,<3"
pre-commit = ">=4.5.1,<5"

[target.linux-64.dependencies]
gxx_linux-64 = ">=13"

[target.osx-64.dependencies]
gxx_osx-64 = ">=13"

[target.osx-arm64.dependencies]
gxx_osx-arm64 = ">=13"
